# Set mouse on
set -g mouse on

### Truecolor support
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

### Pane border colors
set -g pane-border-style fg=brightblack
set -g pane-active-border-style fg=white

### Status bar style with dark gray background
set -g status-style bg=#1c1c1c,fg=white
set -g status-justify centre   # Center elements

### Window list colors
setw -g window-status-style fg=brightwhite,bg=#1c1c1c
setw -g window-status-current-style fg=#1c1c1c,bg=brightwhite

### Messages (search, prompts)
set -g message-style bg=brightblack,fg=white

### Status content
set -g status-left ""
set -g status-right ""
setw -g window-status-format "#[fg=brightblack]#I #[fg=white]#W"
setw -g window-status-current-format "#[fg=#1c1c1c,bg=brightwhite] #I #W "

### Optional: shorten window names
set -g status-interval 2
set -g status-left-length 20
set -g status-right-length 20

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toogle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Swap windows keybindings
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

# Setting fish as default shell
set-option -g default-shell /bin/fish

set -g @plugin 'tmux-plugins/tmp'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
