splash = false
ipc = false

wallpaper {
    monitor = DP-2
    path = ~/.config/backgrounds/saturn-rings.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/backgrounds/saturn-rings.jpg
    fit_mode = cover
}
