splash = false
ipc = false

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/backgrounds/nord-street.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/.config/backgrounds/nord-street.png
    fit_mode = cover
}
