transition = simple

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/backgrounds/dark_pixelart.png
    fit_mode = crop
}

wallpaper {
    monitor = DP-2
    path = ~/.config/backgrounds/dark_pixelart.png
    fit_mode = crop
}
