wallpaper {
    monitor = eDP-1
    path = /home/toast/.config/backgrounds/arch_2.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/toast/.config/backgrounds/arch_2.png
    fit_mode = cover
}
